# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SnapEnv Core Package
site_description: SnapEnv core package.
site_author: 'Abner G Jacobsen'
docs_dir: docs/
repo_name: 'snapenv/snapenv-core'
repo_url: 'https://github.com/snapenv/snapenv-core'
copyright: Copyright &copy; 2023 - 2024 Abner G Jacobsen

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - mike
  - awesome-pages
  - macros:
      modules:
        - mkdocs_macros_adr_summary
  - gen-files:
      scripts:
        - scripts/gen_pages.py  # or any other name or path
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
  - minify:
      minify_html: true
  - glightbox:
      auto_caption: true
      caption_position: bottom

  - autorefs
  - include-markdown
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
  - git-authors:
      enabled: !ENV [CI, false]
  - markdown-exec
  # - search
  - section-index
  - social:
      enabled: !ENV [CI, false]
  - mike:
      canonical_version: "latest"
      version_selector: true
  # - redirects:
  #     redirect_maps:
  #       contributing.md: index.md

# Do not use the nav section in this file but reference to the .pages files
# in the docs/ directory and subdirectories (awesome-pages plugin)
# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
#nav:
#  - Home: index.md

theme:
  name: material
  custom_dir: !relative $docs_dir/overrides
  # custom_dir: mkdocs-overrides
  logo: assets/images/logo.png
  features:
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    # - navigation.indexes
    - navigation.tabs.sticky
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      # accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to automatic mode
  favicon: assets/images/logo.png
  icon:
    # logo: logo
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  extra_css:
  - assets/css/style.css

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abnerjacobsen/
    - icon: fontawesome/brands/github
      link: https://github.com/abnerjacobsen
  version:
    provider: mike
    default:
      - latest
      - dev


markdown_extensions:
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  # - pymdownx.superfences
  # - pymdownx.tabbed:
  #     alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      permalink: "¤"
  - codehilite
  - tables
  - mdx_truly_sane_lists
  - pymdownx.details
